For knowing the entire pipline of how the neural network from the real-world dataset, from training, gradient to the imput variables, to evaluation the neural-netwrok 

We are using breast-cancer dataset for this work.

### importing the dataset

In [2]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


### train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Due to irregularity in the values, we need to scale the values for [0, 1]

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.54205126, -1.39504566, -0.52487462, ..., -0.5138691 ,
         0.89073045,  0.44054749],
       [-0.51161906, -0.80334233, -0.53488605, ..., -1.02156184,
        -0.67398059, -1.1508004 ],
       [-0.12153361,  0.3143195 , -0.07956604, ...,  0.59621945,
         0.45793803,  1.67079225],
       ...,
       [-0.47012061, -0.68772214, -0.37390219, ...,  0.27401825,
         0.51342424,  1.03642188],
       [ 0.03339394,  0.70425426,  0.06339724, ...,  0.30413051,
        -0.33155143, -0.04200775],
       [ 1.75142986,  0.45714444,  1.61436858, ...,  0.4290964 ,
        -1.06079872, -0.70565675]], shape=(455, 30))

In [11]:
y_train

130    B
189    B
7      M
148    B
52     B
      ..
285    B
509    M
485    B
536    M
237    M
Name: diagnosis, Length: 455, dtype: object

In y_train, there are naming which the neural network can't understand it. So, we need to LabelEncode it.

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,

Converting the obtained numpy arrays into pytorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

### Definig the model

In [25]:
class SimpleNN():

    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forwardpass(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    # Here we are using BCE as loss function
    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        loss = (-1) * ( y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

Imp Parameters

In [32]:
learning_rate = 0.1
epochs = 25

Training the pipeline

In [33]:
# creating the model
model = SimpleNN(X_train_tensor)

#define the loop
for epoch in range(epochs):

    # forward pass
    y_pred = model.forwardpass(X_train_tensor)
    
    # loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward()

    # update the parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zeroing the gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoches
    print(f"Epoch : {epoch + 1}, Loss : {loss.item()}")

Epoch : 1, Loss : 3.7868737821761873
Epoch : 2, Loss : 3.659006361105628
Epoch : 3, Loss : 3.5286239041407588
Epoch : 4, Loss : 3.3932622169030315
Epoch : 5, Loss : 3.2567891942042504
Epoch : 6, Loss : 3.117866576173086
Epoch : 7, Loss : 2.9745945535801357
Epoch : 8, Loss : 2.8321940243179955
Epoch : 9, Loss : 2.684342312390929
Epoch : 10, Loss : 2.533010686748697
Epoch : 11, Loss : 2.379870536029842
Epoch : 12, Loss : 2.2261976010819606
Epoch : 13, Loss : 2.0742086081920066
Epoch : 14, Loss : 1.9255201296438056
Epoch : 15, Loss : 1.7790029109747931
Epoch : 16, Loss : 1.6373213750702762
Epoch : 17, Loss : 1.506385593911255
Epoch : 18, Loss : 1.3844654858706384
Epoch : 19, Loss : 1.2747111901425645
Epoch : 20, Loss : 1.1806295161301508
Epoch : 21, Loss : 1.1019583630769219
Epoch : 22, Loss : 1.0375318375155098
Epoch : 23, Loss : 0.9855114265269878
Epoch : 24, Loss : 0.94374337940263
Epoch : 25, Loss : 0.9101053864491049


In [34]:
model.weights

tensor([[-0.2574],
        [ 0.0491],
        [ 0.0149],
        [ 0.1246],
        [-0.0808],
        [-0.4246],
        [ 0.1988],
        [ 0.2420],
        [ 0.2121],
        [-0.1010],
        [ 0.4228],
        [ 0.1422],
        [-0.4583],
        [-0.0706],
        [ 0.5487],
        [ 0.2896],
        [ 0.1641],
        [ 0.3586],
        [ 0.5792],
        [-0.3922],
        [-0.3530],
        [ 0.1932],
        [ 0.4821],
        [-0.0747],
        [-0.1958],
        [ 0.0862],
        [ 0.0463],
        [-0.4669],
        [ 0.5230],
        [ 0.2542]], dtype=torch.float64, requires_grad=True)

In [35]:
model.weights.shape

torch.Size([30, 1])

In [36]:
model.bias

tensor([-0.1102], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [44]:
with torch.no_grad():
    # For the test data, we apply the forward pass
    y_pred = model.forwardpass(X_test_tensor)

    # We need to convert the obtain y_pred value of the X_test data, to 0/1 as to compare that with y_test value 
    y_pred = (y_pred > 0.634).float()

    # Accuracy
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.5837180614471436
