<a href="https://colab.research.google.com/github/shamanth-sr/Learnings-of-Deep-Learning/blob/main/Pytorch-learnings/3.pytorch-nn-module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this learnig we are going to learn about the nn module of Pytorch, by creating a single perceptron architecture which is used for bianry classification problem.

In [22]:
# creating model class

import torch
import torch.nn as nn

class Model(nn.Module):

  # Defining the class imported from nn module
  def __init__(self, num_features):
    super().__init__()
    self.Linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  # Creating a forward pass function
  def forward(self, features):
    out = self.Linear(features)
    out = self.sigmoid(out)
    return out

In [23]:
# create a random dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

#calling the forward pass
''' model.forward(features) can also be used to trigger the forward-pass
function, and there is a internal function called __call__ which will automatically triggers the forward pass itself '''
model.forward(features)



tensor([[0.5401],
        [0.6100],
        [0.5852],
        [0.5292],
        [0.5191],
        [0.5663],
        [0.6451],
        [0.5072],
        [0.4928],
        [0.6049]], grad_fn=<SigmoidBackward0>)

In [18]:
# show model weights
model.Linear.weight

Parameter containing:
tensor([[ 0.2091, -0.2719, -0.1194,  0.1262, -0.2250]], requires_grad=True)

In [19]:
#show model bias
model.Linear.bias

Parameter containing:
tensor([0.3607], requires_grad=True)

Let's install pytorch package from pip, to get the summary of the this single nn.


In [20]:
!pip install torchinfo

In [24]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Now, we make some tiny changes in the network by adding a hidden layer and also increasing the input-features

In [25]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.Linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    self.Linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.Linear1(features)
    out = self.relu(out)

    out = self.Linear2(out)
    out = self.sigmoid(out)

    return out

In [27]:
model = Model(features.shape[1])

model(features)

tensor([[0.5198],
        [0.5061],
        [0.5114],
        [0.5067],
        [0.5263],
        [0.4979],
        [0.4978],
        [0.5189],
        [0.5175],
        [0.5009]], grad_fn=<SigmoidBackward0>)

In [28]:
model.Linear1.weight

Parameter containing:
tensor([[-0.0488,  0.4258, -0.1061, -0.3518, -0.1554],
        [-0.3606,  0.0548,  0.3257,  0.2169,  0.0880],
        [ 0.2158,  0.4209, -0.0576,  0.2194, -0.0485]], requires_grad=True)

In [29]:
model.Linear1.bias

Parameter containing:
tensor([ 0.3788,  0.1879, -0.1311], requires_grad=True)

In [30]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Sequential Pipeline.....

In [35]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [36]:
model = Model(features.shape[1])

model(features)

tensor([[0.4190],
        [0.4279],
        [0.4216],
        [0.4042],
        [0.4240],
        [0.4145],
        [0.4233],
        [0.4170],
        [0.4031],
        [0.4170]], grad_fn=<SigmoidBackward0>)