<a href="https://colab.research.google.com/github/shamanth-sr/Learnings-of-Deep-Learning/blob/main/Pytorch-learnings/4_dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In convention loading of data, there are numerous difficulties,
1. memory ineffecient
2. better convergence

So, for that we are going to use dataset & dataloader, to overcome the these difficulties, which are arised due to the batch-gradient-descent over the dataset. But from now, we will use Mini-batch-gradient-descent.

### Differences-----
1. Dataset Class : knows where the dataset are stored in the memory, and it loads it
2. DataLoader : convert the received data to batches

### 1. Let us create a small dataset of our own

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X, y = make_classification(
    n_samples= 10,
    n_features= 2,
    n_informative= 2,
    n_redundant= 0,
    n_classes= 2,
    random_state= 52
)

In [6]:
X

array([[-0.15326722,  3.10867601],
       [-1.22972207,  1.96389977],
       [-1.22719355, -0.75119097],
       [ 1.19416795, -0.51814433],
       [ 0.5485436 , -0.90716074],
       [-0.25329897,  1.12200225],
       [-0.40324788, -1.42009339],
       [ 0.93522301,  1.62362642],
       [-1.20882998,  1.95654616],
       [ 0.00961969, -1.61872863]])

In [7]:
X.shape

(10, 2)

In [8]:
y

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [9]:
y.shape

(10,)

In [10]:
X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype= torch.long)

In [11]:
X

tensor([[-0.1533,  3.1087],
        [-1.2297,  1.9639],
        [-1.2272, -0.7512],
        [ 1.1942, -0.5181],
        [ 0.5485, -0.9072],
        [-0.2533,  1.1220],
        [-0.4032, -1.4201],
        [ 0.9352,  1.6236],
        [-1.2088,  1.9565],
        [ 0.0096, -1.6187]])

In [12]:
y

tensor([1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In Dataset Class there are 3 major constructs which rule it...
1. __init__ function - initialises the feeatures and labels
2. __len__ function - return the size of the batches
3. getitem function - used to obtain the each element from the batches.

In [13]:
from torch.utils.data import Dataset, DataLoader

In [14]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [15]:
dataset = CustomDataset(X, y)

In [16]:
dataset[2]

(tensor([-1.2272, -0.7512]), tensor(0))

In [17]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [18]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-1.2088,  1.9565],
        [-0.4032, -1.4201]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.2297,  1.9639],
        [-1.2272, -0.7512]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 0.9352,  1.6236],
        [ 1.1942, -0.5181]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 0.5485, -0.9072],
        [ 0.0096, -1.6187]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.1533,  3.1087],
        [-0.2533,  1.1220]])
tensor([1, 1])
--------------------------------------------------


sampler is used in 2 ways
1. sequential sampler (shuffle = False)
It is used in majorly time-series data

2. random sampler (shuffle = True)
It is used for maximum approaches

After random sampling we get the different row values, now we need to combine the values within it using "Collate function"

One of the scenerio,
when we playing with textual data, if a data1 have more data than data2, then we need to provide padding to data2. And that is done through custom code in collate function


Some of the collate function parameters
1. datasets
2. batch_size
3. shuffle
4. num_workers - number of workers neede during process of parallelisation
5. drop_last - dropping/ holding the data in irregular batches
6. custom_collate function